Workaround: Include web3-provider-engine as a dependency to get past truffle issues
Issue here for truffle -
https://github.com/oasislabs/truffle/issues/4

There appears to be a change in the way dependencies are packaged in truffle which
causes users to include packages that their sources don't need to get past truffle
compilation issues. For now, we are including web3-provider-engine as a dep here so
that users of c-k don't have to explicitly include this dependency to get past:

Error: Cannot find module 'bindings'